### PR TITLE
Drop bash and gsed dependencies, add test suite

### PR DESCRIPTION
**Pull request by aclemons**
Drop dependency on bash and require only a posix sh.

Remove gsed dependencies. Should now run with bsd sed without requiring the user to install gnu sed.

Added test suite using bats to avoid regressions.

### CODE REVIEW

**Comment by aclemons** [comment]
What is the target version of solaris here? I know `/bin/sh` on Solaris 10 does not support `$()` but only \`\` which was changed in 7ff3e2f. If you want to support Solaris 10, we'd have to convert the `$()` usage back to \`\`.

**Comment by ValeriyKr** [comment]
Sorry for this big delay, but I really couldn't merge this pull-request.

It's great job and I like it. But I'll make few fixes.

There is problem with interruption by ^C. It have been solved with `trap`.

And yes, I'm using Solaris 10. So, your changes will be merged when I'll fix `$()`s.

**Comment by ValeriyKr** [comment]
You know, it's not only one problem.

First, solaris `sed` (without gnu) takes only short labels. It's fixed.

Second, `/^\[[.]\{3\}=/! b inc_end ` doesn't work. `sed` doesn't understand `!` and I need to think about new logic.

Third, `-r` key calls this message:
`./sfb.sh: -r: is not an identifier`

I ran `sh` with `-x` and got this:
```
+ stty -icanon raw -echo min 0 time 4 ignbrk -brkint -ixon isig 
+ read -r key 
              ./sfb.sh: -r: is not an identifier

```
and it broke my terminal a bit.

At this moment I have no idea how to fix last two problems.

**Comment by aclemons** [comment]
The `-r` tells read to not allow `\` to be escape character. I guess we can remove that for now.

**Comment by aclemons** [comment]
Is the goal to make it work with `/usr/bin/sed` or with `/usr/xpg4/bin/sed` (or both) on solaris? There are considerable differences between the two.

**Comment by aclemons** [comment]
I have pushed another commit my branch now. With it, the bats test suite is passing on Solaris 10 with `/usr/bin/sed` and `/usr/xpg4/bin/sed`. Reading the `k` key is still not working. Something is different on Solaris, but I haven't found the root cause of it yet.

**Comment by aclemons** [comment]
Updated again. There is the built in read in `sh` and `/usr/bin/read`. The latter supports the `-r` option but it is not working in combination with the stty settings used. I have removed the `-r` for now and it seems to be working on Solaris fine now. I assume the trap command you added is to reset before exiting?

**Comment by ValeriyKr** [comment]
Yes, trap is exactly for this. Now I have this:
```
old_stty=`stty -g`

# Restore tty and say "Good Bye" before exit
game_over() {
    stty "${old_stty}"
    printf "Game Over\n"
    exit
}

trap "game_over" INT
```
before main loop. And no `stty -g` in main loop.

About `sed`: yes, I need both. I haven't seen your last commit yes, but I'll do it now.

**Comment by ValeriyKr** [comment]
Yes, it works!

You've done the main part of work, it's great. I did few changes and now I am going to accept it.

**Pull request merged**
